### ISSUE TITLE
Broken Link 

### ISSUE THREAD

**Issue by turbotoss** [hundredrabbits/Grimgrains#62]
Broken link: https://grimgrains.com/site/bamboo_powder.html
In https://grimgrains.com/site/uzumaki_hummus_bites.html

Thank you for sharing yourself with me

**Comment by shantih19** [comment]
This seems to have been fixed, it now links to https://grimgrains.com/site/bamboo_charcoal_powder.html

**Comment by rekkabell** [comment]
No actually it wasn't fixed. The bamboo charcoal powder page has always existed, but in the recipe instructions for the tortillas I used the incorrect word 'bamboo powder' and made that same error in the link name. I just forgot to add the word 'charcoal'. 

I've just corrected the link ;). Thanks for bringing this to my attention, seems like I had missed the first broken link report.

**Comment by shantih19** [comment]
> No actually it wasn't fixed. The bamboo charcoal powder page has always existed, but in the recipe instructions for the tortillas I used the incorrect word 'bamboo powder' and made that same error in the link name. I just forgot to add the word 'charcoal'.
> 
> I've just corrected the link ;). Thanks for bringing this to my attention, seems like I had missed the first broken link report.

Oh, I see! I assumed they were referencing to the ingredient image, my bad!
